

* Activities and their resource allocations

We boot into start; start calls main, which calls, in sequence:
 - title
 - select
 - challenge
 - game
 - either victory or gameover, and finally credits

** title

BG1 is a static tilemap

** select

BG1 is our font layer
BG2 will be a rotscale background at some point

OAM:

We have the selector arrow (16x16) followed by the first frame of each
character.  If that character gets selected, we copy in their victory
frame for a second.

Palette 0 should be the selector arrow, followed by a palette for each
visible character.  (If we add more characters, we'll have to
implement pagination, and we won't have enough palettes for the
non-visible characters.)

** challenge

Not implemented, but we want to have two BGs that slide together.

Probably we can have one layer on top with VERSUS in huge letters, but
with a sensible backdrop color, since the backdrop will show through
under the slide-ins.  If we use BG2 for this, we can even do a
rotscale effect on the VERSUS message (spin while scaling up).

BG0 and BG1 will each have a diagonal and some player stuff drawn on
them, but this can all be tiles.

** game

BG1 is the midground, where collision happens.  We might want some
flexibility as to the other backgrounds, but we'll probably usually
have at least a background, and possibly a foreground as well.  The
background might be rotscale, although most won't be so most of the
time we'll want to use a 4-bit tilemap for that.

OAM:

The first two tiles should be the two balloon states, since we will
need both on screen at once.

We'll copy in all the frames for our balloonists for the rest of the
tiles (even if it means some duplication, since they are tiny compared
to our available VRAM).

Palette 1 and 2 should be balloonist 1 and 2's palettes,
respectively.  Their balloons should use their palette.

** victory

One BG on top (above OBJ) for the message, and possibly a scrolling
background (clouds?  stars?) below.

Copy in both balloon states; draw balloons wafting upwards, pop when
start is hit.

** gameover

Single BG tilemap for now.

** credits

We'll probably do some scrolling tilemap layers here.  Either include
a nice font and do the credits as a font layer, or just write the
credits as an image since there aren't many.


* Art resources, as I found them

| File          | Description                                                   |
|---------------+---------------------------------------------------------------|
| ball[1-7].pcx | Balloons                                                      |
| ball[12]e.pcx | Balloon popping                                               |
| bang[12].pcx  | ? Some kind of two-frame explosion                            |
| bg.pcx        | A bad title screen.  Should be ditched.                       |
| blank.pcx     | Blank tile                                                    |
| brick.pcx     | Square brick tile                                             |
| dirt.pcx      | Dirt tile                                                     |
| dude*b.pcx    | "Bumped" frame                                                |
| dude*d.pcx    | Dying frame                                                   |
| dude*r.pcx    | Regular flying frame                                          |
| dude*v.pcx    | Victory frame                                                 |
| dude1*.pcx    | Retsyn / Dude                                                 |
| dude2*.pcx    | Monk guy?                                                     |
| dude3*.pcx    | Alien ant                                                     |
| dude4*.pcx    | Octopus thing (which did have a name)                         |
| dude5*.pcx    | Blue-haired dude holding balloons (no basket)                 |
| dude6*.pcx    | Pink-haired chick, no basket                                  |
| dude7*.pcx    | Myravist in gravy boat                                        |
| dude8*.pcx    | Caveman guy (Randy?)                                          |
| dude9*.pcx    | smiling head with a monocle                                   |
| dude10*.pcx   | dead guy hung from balloons                                   |
| dude11*.pcx   | same, different colors                                        |
| grass*.pcx    | grass tiles (e is an end piece)                               |
| hbspal.pcx    | an image to indicate where palette variations happen on dudes |
| level0.pcx    | a complete level image                                        |
| title.pcx     | a different title image, worse than bg.pcx                    |
| what.pcx      | a composite piece to show elements together                   |
|---------------+---------------------------------------------------------------|

Palette layout:
0-7: fixed? colors
8-15: two four-color groups of variations, from dark to light,
luminance 30, 62, 94, and 126, respectively.

| 0 | transparent |
| 1 | 8 8 8       |
| 2 | 88 88 88    |
| 3 | 168 168 168 |
| 4 | 252 252 248 |
| 5 | 124 120 60  |
| 6 | 176 172 104 |
| 7 | 228 224 152 |

Balloonist frames are 16x16; balloons and tiles are 8x8.

The tilemap ~hbs.map~ was probably produced with ~timhe~, but it's not
exactly clear what the layout is (looks like 32x32 with 8x8 tiles, but
there are still some other bytes whose purpose I don't recall).  It
will probably be faster to import ~mortimer~ from Convergence and use
it to produce a background from the existing tiles.
